import { Character, Skill } from './types';

const makeSkill = (
  id: string, name: string, description: string,
  damage: number, manaCost: number, element: Skill['element'],
  isUltimate = false, comboId?: string, statusEffect?: Skill['statusEffect']
): Skill => ({
  id, name, description, damage, manaCost, element,
  cooldown: isUltimate ? 3 : 1, currentCooldown: 0,
  isUltimate, comboId, statusEffect
});

export const CHARACTERS: Character[] = [
  {
    id: 'vessel',
    class: 'vessel',
    name: 'Итадори Юджи',
    title: 'Сосуд',
    description: 'Физически совершенный человек, вместилище Рёмэн Сукуны.',
    emoji: '👊',
    color: '#FF6B6B',
    glowColor: '#FF0000',
    hp: 420, maxHp: 420,
    mana: 80, maxMana: 80,
    attack: 85, defense: 60, speed: 90,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Одержимость: каждые 3 атаки — Сукуна берёт контроль на 1 ход (+50% урона)',
    lore: 'Поедатель проклятых объектов. Тело как нерушимый сосуд для величайшего проклятия.',
    comboPairs: ['switcher'],
    skills: [
      makeSkill('divergent_fist', 'Дивергентный кулак', 'Удар с задержкой проклятой энергии', 55, 15, 'cursed'),
      makeSkill('black_flash', 'Чёрная вспышка', 'Удар в момент пиковой концентрации проклятия', 90, 25, 'cursed', false, 'black_flash_combo'),
      makeSkill('sukuna_slash', 'Разрез Сукуны', 'Временное подчинение силы Сукуны', 130, 40, 'void', true, undefined, { type: 'curse', duration: 2, value: 20 }),
    ]
  },
  {
    id: 'honored_one',
    class: 'honored_one',
    name: 'Годжо Сатору',
    title: 'Почитаемый',
    description: 'Сильнейший чародей современности с бесконечностью и шестью глазами.',
    emoji: '♾️',
    color: '#00D4FF',
    glowColor: '#00FFFF',
    hp: 340, maxHp: 340,
    mana: 200, maxMana: 200,
    attack: 95, defense: 95, speed: 85,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Бесконечность: 20% шанс полного отражения любой атаки',
    lore: 'Шесть глаз. Бесконечность. Способен уничтожить весь мир в одиночку.',
    skills: [
      makeSkill('blue', 'Синий — притяжение', 'Создаёт зону отрицательной массы, втягивая врага', 60, 20, 'void'),
      makeSkill('red', 'Красный — отталкивание', 'Усиленный обратный метод — взрывное отталкивание', 80, 30, 'divine'),
      makeSkill('hollow_purple', 'Пустотный пурпур', 'Слияние синего и красного — уничтожение реальности', 200, 80, 'void', true, undefined, { type: 'weakened', duration: 3, value: 30 }),
    ]
  },
  {
    id: 'gambler',
    class: 'gambler',
    name: 'Хакари Кинто',
    title: 'Неугомонный игрок',
    description: 'Чародей с техникой Пулевого Клуба — якпот даёт бессмертие.',
    emoji: '🎰',
    color: '#FFD700',
    glowColor: '#FFA500',
    hp: 380, maxHp: 380,
    mana: 120, maxMana: 120,
    attack: 80, defense: 55, speed: 75,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Джекпот: 15% шанс при ударе восстановить 50 HP и удвоить урон',
    lore: 'Живёт ради кайфа. Его расцвет — когда техника прогревается.',
    skills: [
      makeSkill('pachinko_shot', 'Выстрел патинко', 'Проклятые шарики во врага', 50, 10, 'cursed'),
      makeSkill('jackpot', 'Джекпот!', 'Активирует технику — шанс тройного урона', 75, 35, 'cursed', false, undefined, { type: 'empowered', duration: 2, value: 25 }),
      makeSkill('domain_lottery', 'Домен — лотерея', 'Пулевой клуб полного раскрытия', 160, 70, 'domain', true),
    ]
  },
  {
    id: 'ten_shadows',
    class: 'ten_shadows',
    name: 'Фусигуро Мегуми',
    title: 'Десять теней',
    description: 'Чародей с техникой Десяти Теней — призывает проклятых духов.',
    emoji: '🐉',
    color: '#9B59B6',
    glowColor: '#6C3483',
    hp: 360, maxHp: 360,
    mana: 150, maxMana: 150,
    attack: 70, defense: 70, speed: 70,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Тени: каждый убитый враг усиливает следующего призванного духа',
    lore: 'Призывает Восьмидесятиногого, Жабу, Уробороса и самого Маару.',
    skills: [
      makeSkill('divine_dogs', 'Священные псы', 'Пара духов — терзают врага', 55, 20, 'shadow'),
      makeSkill('nue', 'Нуэ — удар молнии', 'Крылатый дух атакует электричеством', 80, 30, 'shadow', false, undefined, { type: 'stun', duration: 1, value: 0 }),
      makeSkill('mahoraga', 'Восемь рукоятей — Маорага', 'Неукрощаемый дух, адаптирующийся к врагу', 180, 90, 'domain', true),
    ]
  },
  {
    id: 'perfection',
    class: 'perfection',
    name: 'Махито',
    title: 'Воплощение',
    description: 'Проклятый дух, преобразующий души через Праздную трансформацию.',
    emoji: '🔮',
    color: '#00FF88',
    glowColor: '#00CC66',
    hp: 300, maxHp: 300,
    mana: 180, maxMana: 180,
    attack: 90, defense: 45, speed: 80,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Праздная трансформация: атаки меняют форму тела врага (−10 защиты)',
    lore: 'Воплощение ненависти людей. Считает людей просто телами для экспериментов.',
    skills: [
      makeSkill('idle_transfigure', 'Праздная трансфигурация', 'Искажение формы врага', 65, 25, 'cursed', false, undefined, { type: 'curse', duration: 2, value: 15 }),
      makeSkill('body_repel', 'Отталкивание тела', 'Взрыв через изменение формы', 85, 35, 'cursed'),
      makeSkill('soul_multiplicity', 'Множественность душ', 'Создание армии деформированных тел', 170, 75, 'domain', true, undefined, { type: 'weakened', duration: 3, value: 25 }),
    ]
  },
  {
    id: 'blood_manipulator',
    class: 'blood_manipulator',
    name: 'Камо Чосо',
    title: 'Манипулятор крови',
    description: 'Получеловек-полупроклятый, мастер манипуляции кровью.',
    emoji: '🩸',
    color: '#C0392B',
    glowColor: '#922B21',
    hp: 390, maxHp: 390,
    mana: 130, maxMana: 130,
    attack: 82, defense: 65, speed: 65,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Кровь: восстанавливает 5% HP за каждую атаку кровяной техникой',
    lore: 'Брат Юджи по крови Сукуны. Его любовь к братьям сильнее смерти.',
    skills: [
      makeSkill('piercing_blood', 'Пронизывающая кровь', 'Сгущённая кровь как снаряд', 70, 20, 'blood'),
      makeSkill('supernova', 'Сверхновая', 'Взрыв кровяных шаров вокруг врага', 95, 40, 'blood', false, undefined, { type: 'bleed', duration: 3, value: 15 }),
      makeSkill('flowing_red_scale', 'Красная чешуя потока', 'Кипячение собственной крови для сверхскорости', 155, 65, 'blood', true),
    ]
  },
  {
    id: 'switcher',
    class: 'switcher',
    name: 'Тодо Аои',
    title: 'Переключатель',
    description: 'Чародей с техникой Книжного червя — мгновенная смена позиций.',
    emoji: '🔄',
    color: '#E67E22',
    glowColor: '#CA6F1E',
    hp: 400, maxHp: 400,
    mana: 100, maxMana: 100,
    attack: 88, defense: 72, speed: 78,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Книжный червь: раз в бой — полностью избежать атаки через обмен позиций',
    lore: 'Бесит всех своим вопросом про тип девушки. Настоящий бро.',
    comboPairs: ['vessel'],
    skills: [
      makeSkill('boogie_woogie', 'Буги-вуги', 'Хлопок — мгновенная смена позиций с врагом', 45, 15, 'physical', false, 'switch_combo'),
      makeSkill('diverge', 'Разделение', 'Удар после смены — двойной урон', 95, 35, 'physical'),
      makeSkill('bro_combo', 'Комбо братанов', 'Совместная атака с Юджи (бонус если он в группе)', 175, 60, 'physical', true),
    ]
  },
  {
    id: 'defense_attorney',
    class: 'defense_attorney',
    name: 'Хигурума Хироми',
    title: 'Адвокат защиты',
    description: 'Бывший адвокат, чья техника проводит судебный процесс над врагом.',
    emoji: '⚖️',
    color: '#BDC3C7',
    glowColor: '#85929E',
    hp: 350, maxHp: 350,
    mana: 160, maxMana: 160,
    attack: 75, defense: 80, speed: 60,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Вердикт: при критическом ударе — враг лишается способности на 1 ход',
    lore: 'Разочаровался в правосудии. Его домен — идеальный суд.',
    skills: [
      makeSkill('judgeman', 'Судья', 'Призыв судьи-духа для оценки вины', 55, 20, 'cursed'),
      makeSkill('confiscation', 'Конфискация', 'Изъятие проклятой техники врага', 70, 30, 'cursed', false, undefined, { type: 'weakened', duration: 2, value: 20 }),
      makeSkill('death_sentence', 'Смертный приговор', 'Домен — полный судебный процесс', 185, 80, 'domain', true, undefined, { type: 'stun', duration: 2, value: 0 }),
    ]
  },
  {
    id: 'cursed_partners',
    class: 'cursed_partners',
    name: 'Ута Ориме',
    title: 'Проклятые партнёры',
    description: 'Чародей с копированием техник и неограниченной проклятой речью.',
    emoji: '🗡️',
    color: '#1ABC9C',
    glowColor: '#17A589',
    hp: 370, maxHp: 370,
    mana: 170, maxMana: 170,
    attack: 92, defense: 68, speed: 82,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Копирование: после получения урона — 30% шанс скопировать умение врага',
    lore: 'Обещание Рике. Самый сильный чародей первого курса.',
    skills: [
      makeSkill('rika_strike', 'Удар Рики', 'Атака духа Рики Ориме', 65, 20, 'cursed'),
      makeSkill('copy_technique', 'Копирование техники', 'Копирует последнее умение врага', 80, 35, 'cursed'),
      makeSkill('true_rika', 'Истинная Рика', 'Полное раскрытие духа Рики — безграничная мощь', 190, 85, 'domain', true, undefined, { type: 'empowered', duration: 2, value: 40 }),
    ]
  },
  {
    id: 'puppet_master',
    class: 'puppet_master',
    name: 'Гэто Сугуру',
    title: 'Кукловод',
    description: 'Поглощает проклятых духов и использует их как оружие.',
    emoji: '👁️',
    color: '#8E44AD',
    glowColor: '#6C3483',
    hp: 360, maxHp: 360,
    mana: 190, maxMana: 190,
    attack: 78, defense: 62, speed: 68,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Поглощение: каждый убитый враг пополняет арсенал духов',
    lore: 'Ненавидит немагов. Ради своих верит в самое страшное.',
    skills: [
      makeSkill('cursed_spirit_summon', 'Призыв проклятого духа', 'Выпускает поглощённого духа', 60, 20, 'cursed'),
      makeSkill('puppet_control', 'Управление куклой', 'Захватывает контроль над полем', 85, 40, 'cursed', false, undefined, { type: 'curse', duration: 2, value: 10 }),
      makeSkill('maximum_uzumaki', 'Максимум: Узумаки', 'Выпускает всех духов одновременно', 180, 85, 'domain', true, undefined, { type: 'weakened', duration: 3, value: 35 }),
    ]
  },
  {
    id: 'head_of_hei',
    class: 'head_of_hei',
    name: 'Зенин Наоя',
    title: 'Глава рода Хэй',
    description: 'Чародей клана Зенин с техникой Пространственно-пропорционального насилия.',
    emoji: '⚡',
    color: '#F39C12',
    glowColor: '#D68910',
    hp: 345, maxHp: 345,
    mana: 145, maxMana: 145,
    attack: 93, defense: 58, speed: 95,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Скорость: самый быстрый чародей — всегда ходит первым',
    lore: 'Высокомерный и смертоносный. Считает себя непобедимым.',
    skills: [
      makeSkill('propulsion', 'Пропульсия', 'Сверхскоростной удар', 70, 15, 'physical'),
      makeSkill('spatial_ratio', 'Пространственное соотношение', 'Искажение пространства вокруг врага', 90, 35, 'physical', false, undefined, { type: 'stun', duration: 1, value: 0 }),
      makeSkill('zenin_domain', 'Домен клана Зенин', 'Неотразимая атака высшего ранга', 170, 70, 'domain', true),
    ]
  },
  {
    id: 'salaryman',
    class: 'salaryman',
    name: 'Нанами Кенто',
    title: 'Офисный работник',
    description: 'Чародей-профессионал с техникой Соотношения.',
    emoji: '💼',
    color: '#2ECC71',
    glowColor: '#27AE60',
    hp: 395, maxHp: 395,
    mana: 110, maxMana: 110,
    attack: 80, defense: 78, speed: 65,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Рабочий: в сверхурочное время (после 5 хода) урон +30%',
    lore: 'Ненавидит сверхурочную работу. Но всегда доводит дело до конца.',
    skills: [
      makeSkill('ratio_technique', 'Техника соотношения', 'Удар по слабой точке 7:3', 75, 20, 'physical'),
      makeSkill('collapse', 'Обрушение', 'Разрушение структуры тела врага', 95, 40, 'physical', false, undefined, { type: 'bleed', duration: 2, value: 20 }),
      makeSkill('overtime', 'Сверхурочные', 'Полная мощь профессионала', 165, 65, 'physical', true, undefined, { type: 'weakened', duration: 2, value: 25 }),
    ]
  },
  {
    id: 'locust',
    class: 'locust',
    name: 'Кузнечик',
    title: 'Проклятый дух',
    description: 'Особое проклятое существо класса S с мощными физическими атаками.',
    emoji: '🦗',
    color: '#27AE60',
    glowColor: '#1E8449',
    hp: 330, maxHp: 330,
    mana: 100, maxMana: 100,
    attack: 88, defense: 50, speed: 92,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Рой: каждые 3 удара — дополнительная атака роем без затрат маны',
    lore: 'Один из особых проклятых духов. Примитивная ярость насекомого.',
    skills: [
      makeSkill('swarm', 'Рой', 'Атака тысячами насекомых', 60, 10, 'cursed'),
      makeSkill('locust_leap', 'Прыжок кузнечика', 'Сверхскоростной удар сверху', 85, 25, 'physical'),
      makeSkill('plague', 'Нашествие', 'Облако проклятых насекомых', 155, 60, 'cursed', true, undefined, { type: 'curse', duration: 3, value: 20 }),
    ]
  },
  {
    id: 'star_rage',
    class: 'star_rage',
    name: 'Цукимо Юки',
    title: 'Звёздная ярость',
    description: 'Специальный чародей ранга 1 с техникой Звёздного гнева.',
    emoji: '⭐',
    color: '#E91E63',
    glowColor: '#C2185B',
    hp: 355, maxHp: 355,
    mana: 175, maxMana: 175,
    attack: 87, defense: 67, speed: 73,
    level: 1, exp: 0, expToNext: 100,
    passiveBonus: 'Масса звезды: накапливает силу — каждая атака усиливает следующую',
    lore: 'Свободный дух. Ищет способ победить проклятия без порождения новых.',
    skills: [
      makeSkill('star_mass', 'Звёздная масса', 'Удар с массой небесного тела', 68, 20, 'divine'),
      makeSkill('gravity_well', 'Гравитационный колодец', 'Притягивает врага и дробит гравитацией', 90, 35, 'divine', false, undefined, { type: 'weakened', duration: 2, value: 20 }),
      makeSkill('black_hole_domain', 'Домен — чёрная дыра', 'Сжатие реальности в точку', 195, 88, 'domain', true, undefined, { type: 'stun', duration: 2, value: 0 }),
    ]
  },
];

export const getCharacterById = (id: string) => CHARACTERS.find(c => c.id === id);
