import { Location, Quest, Item } from './types';

export const ITEMS: Item[] = [
  { id: 'cursed_bandage', name: 'Проклятый бинт', description: 'Восстанавливает 80 HP', emoji: '🩹', type: 'consumable', rarity: 'common', usable: true, effect: 'heal_80', quantity: 3 },
  { id: 'mana_crystal', name: 'Кристалл ПЭ', description: 'Восстанавливает 5 Проклятой Энергии', emoji: '💎', type: 'consumable', rarity: 'common', usable: true, effect: 'mana_50', quantity: 2 },
  { id: 'elixir', name: 'Эликсир силы', description: 'Усиление на 3 раунда', emoji: '⚗️', type: 'consumable', rarity: 'rare', usable: true, effect: 'buff_attack', quantity: 1 },
  { id: 'sukuna_finger', name: 'Палец Сукуны', description: 'Легендарный объект. Огромная сила.', emoji: '☠️', type: 'cursed_object', rarity: 'legendary', stats: { attack: 20, hp: 50 } },
  { id: 'wooden_sword', name: 'Деревянный меч', description: 'Простое оружие', emoji: '🗡️', type: 'weapon', rarity: 'common', stats: { attack: 8 } },
  { id: 'cursed_blade', name: 'Проклятый клинок', description: 'Наполнен проклятой энергией', emoji: '⚔️', type: 'weapon', rarity: 'rare', stats: { attack: 18 } },
  { id: 'school_uniform', name: 'Форма учеников', description: 'Защита и символ', emoji: '👘', type: 'armor', rarity: 'common', stats: { defense: 10 } },
  { id: 'cursed_armor', name: 'Проклятая броня', description: 'Броня из проклятых волокон', emoji: '🛡️', type: 'armor', rarity: 'epic', stats: { defense: 25, hp: 40 } },
  { id: 'divergent_scroll', name: 'Свиток дивергенции', description: 'Усиливает технику', emoji: '📜', type: 'technique_scroll', rarity: 'rare', stats: { attack: 12 } },
  { id: 'six_eyes_blindfold', name: 'Повязка Годжо', description: 'Сдерживает бесконечность', emoji: '🕶️', type: 'armor', rarity: 'legendary', stats: { defense: 35, mana: 80 } },
];

export const WORLD_LOCATIONS: Location[] = [
  {
    id: 'jujutsu_high', name: 'Техническая школа Джудзюцу',
    description: 'Главная база чародеев Японии. Безопасное место для подготовки.',
    emoji: '🏫', biome: 'school',
    x: 50, y: 50, minLevel: 1,
    enemyIds: [], unlocked: true, cleared: false,
    connectedTo: ['shibuya_outskirts', 'detention_center'],
  },
  {
    id: 'shibuya_outskirts', name: 'Окраины Сибуя',
    description: 'Проклятия появились в жилых кварталах. Первые задания чародеев.',
    emoji: '🏙️', biome: 'urban',
    x: 68, y: 42, minLevel: 1,
    enemyIds: ['small_curse', 'small_curse', 'medium_curse', 'rogue_sorcerer'],
    unlocked: true, cleared: false,
    connectedTo: ['jujutsu_high', 'shibuya_center', 'yokohama_port'],
  },
  {
    id: 'detention_center', name: 'Исправительная колония',
    description: 'Место заключения чародеев. Опасные сокамерники.',
    emoji: '⛓️', biome: 'prison',
    x: 35, y: 60, minLevel: 2,
    enemyIds: ['rogue_sorcerer', 'medium_curse', 'grade2_curse'],
    unlocked: true, cleared: false,
    connectedTo: ['jujutsu_high', 'underground_prison'],
  },
  {
    id: 'shibuya_center', name: 'Центр Сибуя — Инцидент',
    description: 'Место великого инцидента. Проклятая энергия зашкаливает.',
    emoji: '🌆', biome: 'urban',
    x: 72, y: 30, minLevel: 3,
    enemyIds: ['grade2_curse', 'grade1_curse', 'rogue_sorcerer'],
    bossId: 'hanami',
    unlocked: false, cleared: false,
    connectedTo: ['shibuya_outskirts', 'gojo_prison'],
  },
  {
    id: 'yokohama_port', name: 'Порт Йокогама',
    description: 'Морские проклятия атакуют грузовые суда.',
    emoji: '⚓', biome: 'ocean',
    x: 80, y: 55, minLevel: 2,
    enemyIds: ['medium_curse', 'grade2_curse', 'grade2_curse'],
    unlocked: false, cleared: false,
    connectedTo: ['shibuya_outskirts', 'cursed_forest'],
  },
  {
    id: 'cursed_forest', name: 'Проклятый лес',
    description: 'Древний лес, насыщенный тысячелетней проклятой энергией.',
    emoji: '🌲', biome: 'forest',
    x: 88, y: 68, minLevel: 3,
    enemyIds: ['grade2_curse', 'grade1_curse'],
    bossId: 'jogo',
    unlocked: false, cleared: false,
    connectedTo: ['yokohama_port', 'death_painting_lair'],
  },
  {
    id: 'underground_prison', name: 'Подземная тюрьма',
    description: 'Глубочайшая тюрьма для опаснейших существ.',
    emoji: '🏚️', biome: 'dungeon',
    x: 28, y: 75, minLevel: 4,
    enemyIds: ['grade1_curse', 'rogue_sorcerer'],
    bossId: 'choso_clone',
    unlocked: false, cleared: false,
    connectedTo: ['detention_center', 'kings_palace'],
  },
  {
    id: 'death_painting_lair', name: 'Логово картин смерти',
    description: 'Обитель полулюдей-полупроклятых. Мрачное место.',
    emoji: '🖼️', biome: 'dungeon',
    x: 82, y: 82, minLevel: 5,
    enemyIds: ['special_grade_curse', 'grade1_curse'],
    unlocked: false, cleared: false,
    connectedTo: ['cursed_forest', 'gojo_prison'],
  },
  {
    id: 'gojo_prison', name: 'Тюрьма Годжо — Коробка',
    description: 'Место заточения Сильнейшего. Пространство вне пространства.',
    emoji: '📦', biome: 'void',
    x: 55, y: 20, minLevel: 6,
    enemyIds: ['special_grade_curse', 'special_grade_curse'],
    unlocked: false, cleared: false,
    connectedTo: ['shibuya_center', 'death_painting_lair', 'kings_palace'],
  },
  {
    id: 'kings_palace', name: 'Дворец Короля проклятий',
    description: 'Финальное испытание. Здесь обитает Рёмэн Сукуна.',
    emoji: '👑', biome: 'palace',
    x: 50, y: 8, minLevel: 8,
    enemyIds: ['special_grade_curse'],
    bossId: 'sukuna',
    unlocked: false, cleared: false,
    connectedTo: ['gojo_prison', 'underground_prison'],
  },
];

export const QUESTS: Quest[] = [
  {
    id: 'first_mission', title: 'Первое задание', grade: 'D',
    description: 'Устрани проклятия в окраинах Сибуя.',
    objective: 'Победи 3 малых проклятия',
    progress: 0, required: 3,
    reward: { exp: 150, gold: 100, items: [ITEMS[0]] },
    completed: false, active: true, type: 'kill',
  },
  {
    id: 'cleanse_shibuya', title: 'Очистить Сибуя', grade: 'C',
    description: 'Район захвачен. Помоги жителям.',
    objective: 'Победи 5 проклятий любого ранга',
    progress: 0, required: 5,
    reward: { exp: 300, gold: 200, items: [ITEMS[6]] },
    completed: false, active: false, type: 'kill',
  },
  {
    id: 'investigate_forest', title: 'Расследование леса', grade: 'B',
    description: 'В лесу зафиксирована особая активность.',
    objective: 'Посети Проклятый лес',
    progress: 0, required: 1,
    reward: { exp: 500, gold: 400, items: [ITEMS[5]] },
    completed: false, active: false, type: 'explore',
  },
  {
    id: 'hunt_jogo', title: 'Охота на Джого', grade: 'A',
    description: 'Уничтожь особого проклятого духа.',
    objective: 'Победи Джого',
    progress: 0, required: 1,
    reward: { exp: 800, gold: 600, items: [ITEMS[2], ITEMS[7]] },
    completed: false, active: false, type: 'kill',
  },
  {
    id: 'final_battle', title: 'Король проклятий', grade: 'S',
    description: 'Встреть Сукуну лицом к лицу.',
    objective: 'Победи Рёмэн Сукуну',
    progress: 0, required: 1,
    reward: { exp: 9999, gold: 9999, items: [ITEMS[9]] },
    completed: false, active: false, type: 'kill',
  },
];
